package com.example.demo.entities;
// Generated May 22, 2022, 5:50:18 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Act generated by hbm2java
 */
@Entity
@Table(name = "act", schema = "dbo", catalog = "FirstProject1")
@AssociationOverrides({ @AssociationOverride(name = "id.movie", joinColumns = @JoinColumn(name = "movie_id", nullable = false)),
	@AssociationOverride(name = "id.actor", joinColumns = @JoinColumn(name = "actor_id", nullable = false)) })
public class Act  {

	private ActId id = new ActId();
	private String name;

	public Act() {
	}

	public Act(ActId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	public ActId getId() {
		return this.id;
	}

	public void setId(ActId id) {
		this.id = id;
	}

	@Transient
	public Actor getActor() {
		return getId().getActor();
	}

	public void setActor(Actor actor) {
		id.setActor(actor);
	}

	@Transient
	public Movie getMovie() {
		return getId().getMovie();
	}

	public void setMovie(Movie movie) {
		id.setMovie(movie);
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
