package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Act generated by hbm2java
 */
@Entity
@Table(name = "act", schema = "dbo", catalog = "FirstProject")
public class Act implements java.io.Serializable {

	private ActId id;
	private Actor actor;
	private Movie movie;
	private String name;

	public Act() {
	}

	public Act(ActId id, Actor actor, Movie movie, String name) {
		this.id = id;
		this.actor = actor;
		this.movie = movie;
		this.name = name;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "movieId", column = @Column(name = "movie_id", nullable = false, length = 36)),
			@AttributeOverride(name = "actorId", column = @Column(name = "actor_id", nullable = false)) })
	public ActId getId() {
		return this.id;
	}

	public void setId(ActId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actor_id", nullable = false, insertable = false, updatable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false, insertable = false, updatable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
