package com.example.demo.entities;
// Generated May 22, 2022, 5:50:18 PM by Hibernate Tools 4.3.6.Final


import java.io.Serializable;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ActId generated by hbm2java
 */
@Embeddable
public class ActId implements Serializable {

	private Movie movie;
	private Actor actor;

	public ActId() {
	}

	

	public ActId(Movie movie, Actor actor) {
		this.movie = movie;
		this.actor = actor;
	}


	@ManyToOne(cascade = CascadeType.ALL)
	@JsonIgnore
	public Movie getMovie() {
		return movie;
	}



	public void setMovie(Movie movie) {
		this.movie = movie;
	}


	@ManyToOne(cascade = CascadeType.ALL)
	@JsonIgnore
	public Actor getActor() {
		return actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	
}
