package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActId generated by hbm2java
 */
@Embeddable
public class ActId implements java.io.Serializable {

	private String movieId;
	private int actorId;

	public ActId() {
	}

	public ActId(String movieId, int actorId) {
		this.movieId = movieId;
		this.actorId = actorId;
	}

	@Column(name = "movie_id", nullable = false, length = 36)
	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	@Column(name = "actor_id", nullable = false)
	public int getActorId() {
		return this.actorId;
	}

	public void setActorId(int actorId) {
		this.actorId = actorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActId))
			return false;
		ActId castOther = (ActId) other;

		return ((this.getMovieId() == castOther.getMovieId()) || (this.getMovieId() != null
				&& castOther.getMovieId() != null && this.getMovieId().equals(castOther.getMovieId())))
				&& (this.getActorId() == castOther.getActorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMovieId() == null ? 0 : this.getMovieId().hashCode());
		result = 37 * result + this.getActorId();
		return result;
	}

}
