package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "actor", schema = "dbo", catalog = "FirstProject")
public class Actor implements java.io.Serializable {

	private Integer actorId;
	private int name;
	private Set<Act> acts = new HashSet<Act>(0);

	public Actor() {
	}

	public Actor(int name) {
		this.name = name;
	}

	public Actor(int name, Set<Act> acts) {
		this.name = name;
		this.acts = acts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "actor_id", unique = true, nullable = false)
	public Integer getActorId() {
		return this.actorId;
	}

	public void setActorId(Integer actorId) {
		this.actorId = actorId;
	}

	@Column(name = "name", nullable = false)
	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actor")
	public Set<Act> getActs() {
		return this.acts;
	}

	public void setActs(Set<Act> acts) {
		this.acts = acts;
	}

}
