package com.example.demo.entities;
// Generated May 22, 2022, 5:50:18 PM by Hibernate Tools 4.3.6.Final


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "actor", schema = "dbo", catalog = "FirstProject1", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Actor  {

	private Integer actorId;
	private String name;
	private Set<Act> acts = new HashSet<Act>(0);

	public Actor() {
	}

	public Actor(String name) {
		this.name = name;
	}

	public Actor(String name, Set<Act> acts) {
		this.name = name;
		this.acts = acts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "actor_id", unique = true, nullable = false)
	public Integer getActorId() {
		return this.actorId;
	}

	public void setActorId(Integer actorId) {
		this.actorId = actorId;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.actor", cascade = CascadeType.ALL)
	@JsonIgnore
	public Set<Act> getActs() {
		return this.acts;
	}

	public void setActs(Set<Act> acts) {
		this.acts = acts;
	}

}
