package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", schema = "dbo", catalog = "FirstProject")
public class Country implements java.io.Serializable {

	private Integer countryId;
	private String countryName;
	private Set<Movie> movies = new HashSet<Movie>(0);

	public Country() {
	}

	public Country(String countryName) {
		this.countryName = countryName;
	}

	public Country(String countryName, Set<Movie> movies) {
		this.countryName = countryName;
		this.movies = movies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "country_id", unique = true, nullable = false)
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "country_name", nullable = false, length = 100)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JsonIgnore
	@JoinTable(name = "made_of", schema = "dbo", catalog = "FirstProject", joinColumns = {
			@JoinColumn(name = "country_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "movie_id", nullable = false, updatable = false) })
	public Set<Movie> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<Movie> movies) {
		this.movies = movies;
	}

	@Override
	public String toString() {
		return "Country [countryId=" + countryId + ", countryName=" + countryName + ", movies=" + movies + "]";
	}
	
}
