package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Director generated by hbm2java
 */
@Entity
@Table(name = "director", schema = "dbo", catalog = "FirstProject")
public class Director implements java.io.Serializable {

	private Integer directorId;
	private String name;
	private Set<Movie> movies = new HashSet<Movie>(0);

	public Director() {
	}

	public Director(String name) {
		this.name = name;
	}

	public Director(String name, Set<Movie> movies) {
		this.name = name;
		this.movies = movies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "director_id", unique = true, nullable = false)
	public Integer getDirectorId() {
		return this.directorId;
	}

	public void setDirectorId(Integer directorId) {
		this.directorId = directorId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "make", schema = "dbo", catalog = "FirstProject", joinColumns = {
			@JoinColumn(name = "director_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "movie_id", nullable = false, updatable = false) })
	public Set<Movie> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<Movie> movies) {
		this.movies = movies;
	}

}
