package com.example.demo.entities;
// Generated May 22, 2022, 5:50:18 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Episodes generated by hbm2java
 */
@Entity
@Table(name = "episodes", schema = "dbo", catalog = "FirstProject1")
public class Episodes  {

	private Integer episodesId;
	private Set<Server> servers = new HashSet<Server>(0);

	public Episodes() {
	}

	public Episodes(Set<Server> servers) {
		this.servers = servers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "episodes_id", unique = true, nullable = false)
	public Integer getEpisodesId() {
		return this.episodesId;
	}

	public void setEpisodesId(Integer episodesId) {
		this.episodesId = episodesId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "episodes")
	public Set<Server> getServers() {
		return this.servers;
	}

	public void setServers(Set<Server> servers) {
		this.servers = servers;
	}

//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "episodeses")
//	public Set<Movie> getMovies() {
//		return this.movies;
//	}
//
//	public void setMovies(Set<Movie> movies) {
//		this.movies = movies;
//	}

}
