package com.example.demo.entities;
// Generated May 22, 2022, 5:50:18 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Modified generated by hbm2java
 */
@Entity
@Table(name = "modified", schema = "dbo", catalog = "FirstProject1")
public class Modified  {

	private UUID movieId;
	private Movie movie;
	private String time;

	public Modified() {
	}

	public Modified(Movie movie, String time) {
		this.movie = movie;
		this.time = time;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "movie"))
	@Id
	@GeneratedValue(generator = "generator")
	@Type(type = "org.hibernate.type.UUIDCharType")
	@Column(name = "movie_id", unique = true, nullable = false)
	public UUID getMovieId() {
		return this.movieId;
	}

	public void setMovieId(UUID movieId) {
		this.movieId = movieId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@PrimaryKeyJoinColumn
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "time", nullable = false, length = 50)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
