package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Modified generated by hbm2java
 */
@Entity
@Table(name = "modified", schema = "dbo", catalog = "FirstProject")
public class Modified implements java.io.Serializable {

	
	private UUID movieId;
	private Movie movie;
	private String time;

	public Modified() {
	}

	public Modified(Movie movie, String time) {
		this.movie = movie;
		this.time = time;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "movie"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "movie_id", unique = true, nullable = false, length = 36)
	@Type(type = "org.hibernate.type.UUIDCharType")
	public UUID getMovieId() {
		return this.movieId;
	}

	public void setMovieId(UUID movieId) {
		this.movieId = movieId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JsonIgnore
	@JoinColumn(name = "movie_id", insertable = false, updatable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "time", nullable = false, length = 50)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Override
	public String toString() {
		return "Modified [movieId=" + movieId + ", movie=" + movie + ", time=" + time + "]";
	}
	

}
