package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.MapKey;
import javax.persistence.MapsId;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.LazyToOne;
import org.hibernate.annotations.LazyToOneOption;
import org.hibernate.annotations.Type;

import com.example.demo.DTO.MovieDTO;

import lombok.Builder;

/**
 * Movie generated by hbm2java
 */
@Entity
@Builder
@Table(name = "movie", schema = "dbo", catalog = "FirstProject")
public class Movie implements java.io.Serializable {

	private UUID movieId;
	private String name;
	private String originName;
	private String content;
	private String type;
	private String status;
	private String thumbUrl;
	private String time;
	private String episodeCurrent;
	private String episodeTotal;
	private String quality;
	private int year;
	private String trailerUrl;
	private String lang;
	private String notify;
	private String showtimes;
	private String slug;
	private String isCopyright;
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Country> countries = new HashSet<Country>(0);
	private Set<Director> directors = new HashSet<Director>(0);
	private Modified modified;
	private Set<Act> acts = new HashSet<Act>(0);
	private Set<Episodes> episodeses = new HashSet<Episodes>(0);

	public Movie() {
	}

	public Movie(UUID movieId, String name, String originName, String content, String type, String status,
			String thumbUrl, String time, String episodeCurrent, String episodeTotal, String quality, int year,
			String trailerUrl, String lang, String notify, String showtimes, String slug, String isCopyright) {
		this.movieId = movieId;
		this.name = name;
		this.originName = originName;
		this.content = content;
		this.type = type;
		this.status = status;
		this.thumbUrl = thumbUrl;
		this.time = time;
		this.episodeCurrent = episodeCurrent;
		this.episodeTotal = episodeTotal;
		this.quality = quality;
		this.year = year;
		this.trailerUrl = trailerUrl;
		this.lang = lang;
		this.notify = notify;
		this.showtimes = showtimes;
		this.slug = slug;
		this.isCopyright = isCopyright;
	}

	public Movie(UUID movieId, String name, String originName, String content, String type, String status,
			String thumbUrl, String time, String episodeCurrent, String episodeTotal, String quality, int year,
			String trailerUrl, String lang, String notify, String showtimes, String slug, String isCopyright,
			Set<Category> categories, Set<Country> countries, Set<Director> directors, Modified modified, Set<Act> acts,
			Set<Episodes> episodeses) {
		this.movieId = movieId;
		this.name = name;
		this.originName = originName;
		this.content = content;
		this.type = type;
		this.status = status;
		this.thumbUrl = thumbUrl;
		this.time = time;
		this.episodeCurrent = episodeCurrent;
		this.episodeTotal = episodeTotal;
		this.quality = quality;
		this.year = year;
		this.trailerUrl = trailerUrl;
		this.lang = lang;
		this.notify = notify;
		this.showtimes = showtimes;
		this.slug = slug;
		this.isCopyright = isCopyright;
		this.categories = categories;
		this.countries = countries;
		this.directors = directors;
		this.modified = modified;
		this.acts = acts;
		this.episodeses = episodeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Type(type = "org.hibernate.type.UUIDCharType")
	@Column(name = "movie_id", unique = true, nullable = false, length = 36)
	public UUID getMovieId() {
		return this.movieId;
	}

	public void setMovieId(UUID movieId) {
		this.movieId = movieId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "origin_name", nullable = false, length = 300)
	public String getOriginName() {
		return this.originName;
	}

	public void setOriginName(String originName) {
		this.originName = originName;
	}

	@Column(name = "content", nullable = false, length = 800)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "thumb_url", nullable = false, length = 300)
	public String getThumbUrl() {
		return this.thumbUrl;
	}

	public void setThumbUrl(String thumbUrl) {
		this.thumbUrl = thumbUrl;
	}

	@Column(name = "time", nullable = false, length = 20)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "episode_current", nullable = false, length = 50)
	public String getEpisodeCurrent() {
		return this.episodeCurrent;
	}

	public void setEpisodeCurrent(String episodeCurrent) {
		this.episodeCurrent = episodeCurrent;
	}

	@Column(name = "episode_total", nullable = false, length = 50)
	public String getEpisodeTotal() {
		return this.episodeTotal;
	}

	public void setEpisodeTotal(String episodeTotal) {
		this.episodeTotal = episodeTotal;
	}

	@Column(name = "quality", nullable = false, length = 20)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "trailer_url", nullable = false, length = 300)
	public String getTrailerUrl() {
		return this.trailerUrl;
	}

	public void setTrailerUrl(String trailerUrl) {
		this.trailerUrl = trailerUrl;
	}

	@Column(name = "lang", nullable = false, length = 20)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "notify", nullable = false, length = 20)
	public String getNotify() {
		return this.notify;
	}

	public void setNotify(String notify) {
		this.notify = notify;
	}

	@Column(name = "showtimes", nullable = false, length = 100)
	public String getShowtimes() {
		return this.showtimes;
	}

	public void setShowtimes(String showtimes) {
		this.showtimes = showtimes;
	}

	@Column(name = "slug", nullable = false, length = 200)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "is_copyright", nullable = false, length = 20)
	public String getIsCopyright() {
		return this.isCopyright;
	}

	public void setIsCopyright(String isCopyright) {
		this.isCopyright = isCopyright;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "movies",cascade = CascadeType.ALL)
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "movies",cascade = CascadeType.ALL)
	public Set<Country> getCountries() {
		return this.countries;
	}

	public void setCountries(Set<Country> countries) {
		this.countries = countries;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "movies",cascade = CascadeType.ALL)
	public Set<Director> getDirectors() {
		return this.directors;
	}

	public void setDirectors(Set<Director> directors) {
		this.directors = directors;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "movie",cascade = CascadeType.ALL)
	public Modified getModified() {
		return this.modified;
	}

	public void setModified(Modified modified) {
		this.modified = modified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie", cascade = CascadeType.ALL)
	public Set<Act> getActs() {
		return this.acts;
	}

	public void setActs(Set<Act> acts) {
		this.acts = acts;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "movies")
	public Set<Episodes> getEpisodeses() {
		return this.episodeses;
	}

	public void setEpisodeses(Set<Episodes> episodeses) {
		this.episodeses = episodeses;
	}

	public MovieDTO toDto() {
		
		return MovieDTO.builder()
				.name(name)
				.originName(originName)
				.episodeCurrent(episodeCurrent)
				.episodeTotal(episodeTotal)
				.content(content)
				.categories(categories)
				.Act(acts)
				.countries(countries)
				.directors(directors)
				.isCopyright(isCopyright)
				.lang(lang)
				.modifieds(modified)
				.quality(quality)
				.showtimes(showtimes)
				.slug(slug)
				.trailerUrl(trailerUrl)
				.thumbUrl(thumbUrl)
				.episodeses(episodeses)
				.notify(notify)
				.status(status)
				.type(type)
				.year(year)
				.time(time)
				.build();
	}
	
	public void addModified(Modified modi) {
		modi.setMovie(this);
		this.setModified(modi);
	}

}
