package com.example.demo.entities;
// Generated May 6, 2022, 8:01:05 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Server generated by hbm2java
 */
@Entity
@Table(name = "server", schema = "dbo", catalog = "FirstProject")
public class Server implements java.io.Serializable {

	private Integer serverId;
	private Episodes episodes;
	private String serverName;
	private Set<ServerData> serverDatas = new HashSet<ServerData>(0);

	public Server() {
	}

	public Server(Episodes episodes, String serverName) {
		this.episodes = episodes;
		this.serverName = serverName;
	}

	public Server(Episodes episodes, String serverName, Set<ServerData> serverDatas) {
		this.episodes = episodes;
		this.serverName = serverName;
		this.serverDatas = serverDatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "server_id", unique = true, nullable = false)
	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "episodes_id", nullable = false)
	public Episodes getEpisodes() {
		return this.episodes;
	}

	public void setEpisodes(Episodes episodes) {
		this.episodes = episodes;
	}

	@Column(name = "server_name", nullable = false, length = 50)
	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "server",cascade = CascadeType.ALL)
	public Set<ServerData> getServerDatas() {
		return this.serverDatas;
	}

	public void setServerDatas(Set<ServerData> serverDatas) {
		this.serverDatas = serverDatas;
	}

	@Override
	public String toString() {
		return "Server [serverId=" + serverId + ", episodes=" + episodes + ", serverName=" + serverName
				+ ", serverDatas=" + serverDatas + "]";
	}
	
	
}
