package com.example.demo.entities;
// Generated Apr 20, 2022, 5:49:58 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor implements java.io.Serializable {

	private int actorId;
	private String name;
	private Set movies = new HashSet(0);

	public Actor() {
	}

	public Actor(int actorId, String name) {
		this.actorId = actorId;
		this.name = name;
	}

	public Actor(int actorId, String name, Set movies) {
		this.actorId = actorId;
		this.name = name;
		this.movies = movies;
	}

	public int getActorId() {
		return this.actorId;
	}

	public void setActorId(int actorId) {
		this.actorId = actorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getMovies() {
		return this.movies;
	}

	public void setMovies(Set movies) {
		this.movies = movies;
	}

}
