package com.example.demo.entities;
// Generated Apr 20, 2022, 5:49:58 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int categoryId;
	private String type;
	private Set movies = new HashSet(0);

	public Category() {
	}

	public Category(int categoryId, String type) {
		this.categoryId = categoryId;
		this.type = type;
	}

	public Category(int categoryId, String type, Set movies) {
		this.categoryId = categoryId;
		this.type = type;
		this.movies = movies;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getMovies() {
		return this.movies;
	}

	public void setMovies(Set movies) {
		this.movies = movies;
	}

}
