package com.example.demo.entities;
// Generated Apr 20, 2022, 5:49:58 PM by Hibernate Tools 5.6.7.Final

/**
 * Episodes generated by hbm2java
 */
public class Episodes  {

	private int episodeId;
	private Movie movie;
	private String filename;
	private String linkEmbed;
	private String linkM3u8;

	public Episodes() {
	}

	public Episodes(int episodeId, Movie movie) {
		this.episodeId = episodeId;
		this.movie = movie;
	}

	public Episodes(int episodeId, Movie movie, String filename, String linkEmbed, String linkM3u8) {
		this.episodeId = episodeId;
		this.movie = movie;
		this.filename = filename;
		this.linkEmbed = linkEmbed;
		this.linkM3u8 = linkM3u8;
	}

	public int getEpisodeId() {
		return this.episodeId;
	}

	public void setEpisodeId(int episodeId) {
		this.episodeId = episodeId;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getLinkEmbed() {
		return this.linkEmbed;
	}

	public void setLinkEmbed(String linkEmbed) {
		this.linkEmbed = linkEmbed;
	}

	public String getLinkM3u8() {
		return this.linkM3u8;
	}

	public void setLinkM3u8(String linkM3u8) {
		this.linkM3u8 = linkM3u8;
	}

}
